# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
sudo: false

git:
  depth: 2

cache:
  pip: true

branches:
  only:
    - master
    - develop

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.5
      env:
        - TOXENV=flake8
    - os: linux
      python: 2.7
      env:
        - TOXENV=py27
    - os: linux
      python: 3.4
      env:
        - TOXENV=py34
    - os: linux
      python: 3.5
      env:
        - TOXENV=py35
    - os: linux
      python: 3.6
      env:
        - TOXENV=py36
    - os: osx
      language: generic
      env:
        - TOXENV=py27
    - os: osx
      language: generic
      env:
        - TOXENV=py36


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - bash ci/travis/setup.sh

# command to run tests
script:
  - tox -e "${TOXENV}"

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dmccloskey
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    branch: master
    repo: Biosustain/thermodynamics
    condition: $TOXENV == py27

notifications:
  email:
    on_success: never
    on_failure: always
