# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
sudo: false

git:
  depth: 2

cache:
  pip: true

branches:
  only:
    - master
    - develop
    - "/v\\d+\\.\\d+\\.\\d+/"

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.5
      env:
        - TOXENV=flake8
    # - os: linux
    #   python: 2.7
    #   env:
    #     - TOXENV=py27
    - os: linux
      python: 3.4
      env:
        - TOXENV=py34
    - os: linux
      python: 3.5
      env:
        - TOXENV=py35
    - os: linux
      python: 3.6
      env:
        - TOXENV=py36
    - os: osx
      language: generic
      env:
        - TOXENV=py27
    - os: osx
      language: generic
      env:
        - TOXENV=py36


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - bash ci/travis/setup.sh

# command to run tests
script:
  - tox -e "${TOXENV}"

before_deploy:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
        pip install -r docs/requirements.txt;
        make docs && touch _build/html/.nojekyll;
    fi
  - cd $TRAVIS_BUILD_DIR

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: dmccloskey
    password: $PYPI
    on:
      tags: true
      branch: master
      repo: dmccloskey/thermodynamics
      condition: $TRAVIS_PYTHON_VERSION == "3.6"
  - provider: pages
    local_dir: docs/_build/html
    skip_cleanup: true
    github_token: $GH_TOKEN # Set in travis-ci.org dashboard
    target-branch: gh-pages
    on:
      branch:
        - master
        - develop
      condition: $TRAVIS_PYTHON_VERSION == "3.6"
      repo: dmccloskey/thermodynamics

notifications:
  email:
    on_success: never
    on_failure: never
